CONFIG_ZMK_BLE=y

# I2C + PCF8574
CONFIG_I2C=y
CONFIG_GPIO=y
CONFIG_GPIO_PCF8574=y

# ZMK-managed USB CDC ACM logging
CONFIG_ZMK_USB_LOGGING=y

# Verbose logs from the drivers we care about
CONFIG_GPIO_LOG_LEVEL_DBG=y
CONFIG_I2C_LOG_LEVEL_DBG=y
CONFIG_KSCAN_LOG_LEVEL_DBG=y
